workouse_availability_notifier_plugin_admin:
  resource: "@WorkouseAvailabilityNotifierPlugin/Resources/config/admin_routing.yml"
  prefix: /admin

workouse_availability_notifier_plugin_shop:
  resource: "@WorkouseAvailabilityNotifierPlugin/Resources/config/shop_routing.yml"
  prefix: /{_locale}
  requirements:
    _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
